### ISSUE TITLE
Toolchain archive extracting bug

### ISSUE THREAD

**Issue by DMHYT** [zheka2304/innercore-mod-toolchain#11]
# **When the toolchain archive is downloaded, the toolchain repo itself is being put into my project folder (Screenshot)**
***
![Скриншот 07-09-2021 210554](https://user-images.githubusercontent.com/63312903/132391024-75daceab-42a6-4d62-bc21-c6d700bc628d.jpg)

**Comment by rislaed** [comment]
Neither download nor update can download update archive affecting your projects anymore. #16
