### ISSUE TITLE
Extracting GCC and it installation crashes

### ISSUE THREAD

**Issue by weifeng233** [zheka2304/innercore-mod-toolchain#17]
i have no idea how it happend, i even run it with as administrator
![image](https://user-images.githubusercontent.com/63801758/202848786-0347fcc7-4379-43b4-b350-06fb7374e863.png)
so i extracted the ndk.zip and deleted related python code to skip it
then i found the libpython2.7.dll was readonly, but i download the ndk three times, there should be something to slove it when it happend

**Comment by rislaed** [comment]
I can't reproduce your issue on Windows 11 10.0.22000.778, can you provide more details about your environment or retry installation with pull request: https://github.com/zheka2304/innercore-mod-toolchain/pull/20#discussion_r1027371930

**Comment by weifeng233** [comment]
i'm Windows 11 Insider Preview Build 22623.891, maybe it's a insider version bug

now it can extract the ndk successfully, but when removing temp it got permission error again, maybe can put the remove at the last step, or let user to remove the temp file if error occur
i have tried many times and it always ends in one of these two files:
![image](https://user-images.githubusercontent.com/63801758/203085901-7c4bd156-6921-4172-b55a-6ef316e50bd9.png)
![image](https://user-images.githubusercontent.com/63801758/203086566-5e0ca57c-6bdc-4df0-a263-8c17e18411e2.png)

btw, the downloaded ndk file's size was miscalculated

**Comment by rislaed** [comment]
Depending on [.ZIP File Format Specification](https://pkware.cachefly.net/webdocs/APPNOTE/APPNOTE-6.3.9.TXT) most likely manually appending -w--w- flags will help. Probably issue encours at some archivators, but in our case force-appending attributes must help. Thanks for advance!

**Comment by weifeng233** [comment]
![image](https://user-images.githubusercontent.com/63801758/203306969-4325f29f-a3c2-4115-896d-48d13ab97db7.png)
finally it worked perfectly, expect the ndk was installed twice

**Comment by rislaed** [comment]
Thank you for your active assistance, owing to you the toolchain works even more stable and installs a native compiler for all architectures at once :heart_eyes:
