### ISSUE TITLE
select jdk manuallly

### ISSUE THREAD

**Issue by weifeng233** [zheka2304/innercore-mod-toolchain#21]
i have multiple versions of jdk on my computer, and default is jdk18(i have to use this version for other apps), but the toolchain use java command directly, which will cause error
so maybe it can let user to select the right version jdk's path or download jdk1.8 when installing toolchain

**Comment by xsj284** [comment]
![image](https://user-images.githubusercontent.com/72089458/204347965-3bc702e0-6528-4c87-9f68-62dec425fd4f.png)
这样可以设置Java的版本
This allows you to set the version of Java

**Comment by xsj284** [comment]
ctrl+p打开命令面板，打开工作区设置，或者编辑toolchain.code-workspace文件
配置你的Java8路径
ctrl+p opens the command palette, opens workspace settings(JSON), or edits the toolchain.code-workspace file
Configure your Java8 path
![image](https://user-images.githubusercontent.com/72089458/204351044-e127a8e9-471c-4333-8e63-00323d15f692.png)
ctrl+p打开命令面板，打开工作区设置，或者编辑toolchain.code-workspace文件
配置你的Java8路径
![image](https://user-images.githubusercontent.com/72089458/204351568-c9efac80-bd63-453b-af2b-a8639bd8683e.png)

**Comment by rislaed** [comment]
Have you seen [#unsupported-class-file-version-550](https://github.com/zheka2304/innercore-mod-toolchain/blob/master/FAQ.md#unsupported-class-file-version-550) in FAQ? If yes, how this should working? We are using gradlew, that is usually uses your IDE `java`.

**Comment by weifeng233** [comment]
get it, sorry it`s my problem, thank you
