### ISSUE TITLE
Почему используем разделитель пути файла из windows?

### ISSUE THREAD

**Issue by Molybdocene-dichloride** [zheka2304/innercore-mod-toolchain#7]
[ferrocene@arch python]$ python task.py compileNativeDebug
sh: color: команда не найдена
> executing task: compileNativeDebug
failed to get ndk path
download ndk? (Y/N) y
extracting ndk...
installing...
WARNING:__main__:Defaulting to target API 14 (minimum supported target for arm)
Could not find GCC/binutils: /home/ferrocene/.android/dd/innercore-mod-toolchain-master/toolchain-mod/toolchain\temp/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
installation failed with result code: 1
ndk installation is broken, trying to re-install
failed to get ndk path
download ndk? (Y/N)
toolchain\temp -  вот здесь неправильный разделитель пути. 
И в папке появились файлы toolchain\temp и toolchain\temp\ndk.zip
[<img src="https://i.ibb.co/bdBqf2h/2020-12-04-22-49-07.png">]

**Comment by rislaed** [comment]
Now it absolutely fixed.
